// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqhVDNLRrHZxnt9I2WrwYppX-GgFNGCJI',
    appId: '1:481112771239:web:61731acda563bff8dc2982',
    messagingSenderId: '481112771239',
    projectId: 'manual-de-sobrevivencia2-0',
    authDomain: 'manual-de-sobrevivencia2-0.firebaseapp.com',
    databaseURL: 'https://manual-de-sobrevivencia2-0-default-rtdb.firebaseio.com',
    storageBucket: 'manual-de-sobrevivencia2-0.appspot.com',
    measurementId: 'G-YBPHBEGYBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2pGIre-dd4X4TyBwMWZFwsoz2FSd1_lA',
    appId: '1:481112771239:android:cf3bec45d42795abdc2982',
    messagingSenderId: '481112771239',
    projectId: 'manual-de-sobrevivencia2-0',
    databaseURL: 'https://manual-de-sobrevivencia2-0-default-rtdb.firebaseio.com',
    storageBucket: 'manual-de-sobrevivencia2-0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPj6HLoFRDUMjVLcT3PknVU0lcxrFYLQA',
    appId: '1:481112771239:ios:0457b30d881e8093dc2982',
    messagingSenderId: '481112771239',
    projectId: 'manual-de-sobrevivencia2-0',
    databaseURL: 'https://manual-de-sobrevivencia2-0-default-rtdb.firebaseio.com',
    storageBucket: 'manual-de-sobrevivencia2-0.appspot.com',
    iosClientId: '481112771239-h736qq4g6b3dp30jsb9110b2mgn5idrr.apps.googleusercontent.com',
    iosBundleId: 'com.example.manualDeSobrevivencia',
  );
}
